// Code generated by command: go run main.go -out ../../gemm_microkernel_amd64.s -stubs ../../gemm_microkernel_stub_amd64.go -pkg cpu. DO NOT EDIT.

package cpu

// gemmMicroKernel4x16AVX2 computes a 4x16 tile C[r,col] = sum_kk a[r*k+kk]*b[kk*n+col]
// (overwriting C) using AVX2+FMA with the C tile held in registers across the k-loop.
// c, a and b are the tile-local sub-slices; k and n are the A-row and B/C-row strides.
//
//go:noescape
func gemmMicroKernel4x16AVX2(c []float32, a []float32, b []float32, k int, n int)

// gemmMicroKernel1x16AVX2 computes a 1x16 tile C[0,col] = sum_kk a[kk]*b[kk*n+col]
// (overwriting C) using AVX2+FMA, with the two C accumulators held in
// registers across the k-loop. c and a are tile-local sub-slices; n is the
// B-row stride (a is a single row, so its stride k is unused).
//
//go:noescape
func gemmMicroKernel1x16AVX2(c []float32, a []float32, b []float32, k int, n int)
